Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"  
  config.vm.network "forwarded_port", guest: 5000, host: 5000 
  config.vm.network "forwarded_port", guest: 80, host: 8080    
  
  # Senkronize klasör
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  
  # VM kaynakları
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end
  
  # Ansible kurulumu için shell provision
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y ansible
  SHELL
  
  # Ansible provision
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end